-- Anna storefront tables. Run this once in Supabase SQL Editor.
create extension if not exists pgcrypto;

create table if not exists public.products (
  id text primary key,
  sku text not null,
  name text not null,
  category text not null default 'frames',
  price integer not null check (price >= 0),
  image text not null,
  description text,
  material text,
  measurements text,
  shape text,
  fit text,
  badge text,
  colors text[] default '{}',
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  customer_name text not null,
  phone text not null,
  address text not null,
  note text,
  subtotal integer not null check (subtotal >= 0),
  shipping integer not null default 0 check (shipping >= 0),
  total integer not null check (total >= 0),
  status text not null default 'new',
  created_at timestamptz not null default now()
);

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id uuid not null references public.orders(id) on delete cascade,
  product_id text not null,
  product_name text not null,
  unit_price integer not null check (unit_price >= 0),
  quantity integer not null check (quantity > 0),
  created_at timestamptz not null default now()
);

alter table public.products enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;

drop policy if exists "public can read active products" on public.products;
create policy "public can read active products"
  on public.products for select
  using (is_active = true);

drop policy if exists "public can create orders" on public.orders;
create policy "public can create orders"
  on public.orders for insert
  with check (true);

drop policy if exists "public can create order items" on public.order_items;
create policy "public can create order items"
  on public.order_items for insert
  with check (true);

create index if not exists products_category_idx on public.products(category);
create index if not exists order_items_order_id_idx on public.order_items(order_id);
